# Example ESPHome configuration for Bresser Weather Sensor
# Copy this to your ESPHome config directory and customize

substitutions:
  device_name: bresser-weather
  friendly_name: Bresser Weather Station

esphome:
  name: ${device_name}

esp8266:
  board: d1_mini # or esp01_1m for ESP-01

# Required: SPI configuration for CC1101 radio module
spi:
  clk_pin: GPIO14 # D5
  miso_pin: GPIO12 # D6
  mosi_pin: GPIO13 # D7

# External component - use from GitHub after publishing
external_components:
  # After publishing to GitHub, use this:
  # - source: github://YOUR_USERNAME/bresser-esphome@main
  #   components: [ bresser_weather ]

  # For local development:
  - source:
      type: local
      path: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot
  ap:
    ssid: "${device_name} Fallback"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# Optional: Web server for debugging (uses extra memory)
web_server:
  port: 80

# Bresser Weather Sensor Component
bresser_weather:
  temperature:
    name: "Temperature"
  humidity:
    name: "Humidity"
  wind_gust:
    name: "Wind Gust"
  wind_speed:
    name: "Wind Speed"
  wind_direction:
    name: "Wind Direction"
  rain:
    name: "Rain"
  uv:
    name: "UV Index"
  light:
    name: "Light"
  rssi:
    name: "RSSI"
  battery_ok:
    name: "Battery OK"
  sensor_id:
    name: "Sensor ID"
