# Local Development Example
# Use this when developing the component locally

substitutions:
  device_name: bresser-weather
  friendly_name: Bresser Weather Station

esphome:
  name: ${device_name}

esp8266:
  board: d1_mini

# Required: SPI configuration for CC1101
spi:
  clk_pin: GPIO14 # D5
  miso_pin: GPIO12 # D6
  mosi_pin: GPIO13 # D7

# External component - local path for development
external_components:
  - source:
      type: local
      path: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${device_name} Fallback"
    password: !secret fallback_password

captive_portal:

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80

# Bresser Weather Sensor Component
bresser_weather:
  temperature:
    name: "Temperature"
  humidity:
    name: "Humidity"
  wind_gust:
    name: "Wind Gust"
  wind_speed:
    name: "Wind Speed"
  wind_direction:
    name: "Wind Direction"
  rain:
    name: "Rain"
  uv:
    name: "UV Index"
  light:
    name: "Light"
  rssi:
    name: "RSSI"
  battery_ok:
    name: "Battery OK"
  sensor_id:
    name: "Sensor ID"
